-- Clean Up Existing Tables (For development reload)
DROP TABLE IF EXISTS notification_logs CASCADE;
DROP TABLE IF EXISTS approval_history CASCADE;
DROP TABLE IF EXISTS approval_rules CASCADE;
DROP TABLE IF EXISTS shipment_milestones CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS customer_orders CASCADE;
DROP TABLE IF EXISTS stock_transactions CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS warehouse_bins CASCADE;
DROP TABLE IF EXISTS warehouse_shelves CASCADE;
DROP TABLE IF EXISTS warehouse_racks CASCADE;
DROP TABLE IF EXISTS warehouse_zones CASCADE;
DROP TABLE IF EXISTS warehouses CASCADE;
DROP TABLE IF EXISTS quotations CASCADE;
DROP TABLE IF EXISTS rfqs CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS purchase_requests CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

-- 1. Multi-Tenant Organization Structure
CREATE TABLE organizations (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    domain VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departments (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL,
    budget_limit NUMERIC(15, 2) DEFAULT 0.00,
    remaining_budget NUMERIC(15, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. User & Authentication
CREATE TABLE users (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    department_id VARCHAR(50) REFERENCES departments(id),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL, -- SUPER_ADMIN, PROCUREMENT_MANAGER, INVENTORY_MANAGER, WAREHOUSE_MANAGER, LOGISTICS_MANAGER, VENDOR, EMPLOYEE
    status VARCHAR(20) DEFAULT 'PENDING_VERIFICATION', -- ACTIVE, LOCKED, PENDING_VERIFICATION
    phone VARCHAR(20),
    mfa_enabled BOOLEAN DEFAULT FALSE,
    mfa_secret VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    user_id VARCHAR(50) REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    device_info VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Vendors
CREATE TABLE vendors (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) REFERENCES users(id) ON DELETE SET NULL,
    company_name VARCHAR(100) UNIQUE NOT NULL,
    contact_name VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    address TEXT,
    verification_status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    product_categories VARCHAR(255),
    delivery_score NUMERIC(5, 2) DEFAULT 100.00,
    quality_score NUMERIC(5, 2) DEFAULT 100.00,
    cost_score NUMERIC(5, 2) DEFAULT 100.00,
    reliability_score NUMERIC(5, 2) DEFAULT 100.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Procurement Management
CREATE TABLE purchase_requests (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    department_id VARCHAR(50) REFERENCES departments(id),
    requester_id VARCHAR(50) REFERENCES users(id),
    item_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    estimated_cost NUMERIC(12, 2) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, PENDING_APPROVAL, APPROVED, REJECTED, RFQ_STAGE, ORDERED
    approval_level INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rfqs (
    id VARCHAR(50) PRIMARY KEY,
    purchase_request_id VARCHAR(50) REFERENCES purchase_requests(id) ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    deadline TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'OPEN', -- OPEN, CLOSED, AWARDED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quotations (
    id VARCHAR(50) PRIMARY KEY,
    rfq_id VARCHAR(50) REFERENCES rfqs(id) ON DELETE CASCADE,
    vendor_id VARCHAR(50) REFERENCES vendors(id) ON DELETE CASCADE,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    delivery_lead_days INT NOT NULL,
    remarks TEXT,
    status VARCHAR(20) DEFAULT 'SUBMITTED', -- SUBMITTED, REJECTED, ACCEPTED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_orders (
    id VARCHAR(50) PRIMARY KEY,
    purchase_request_id VARCHAR(50) REFERENCES purchase_requests(id),
    vendor_id VARCHAR(50) REFERENCES vendors(id),
    total_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING_ACCEPTANCE', -- PENDING_ACCEPTANCE, ACCEPTED, SHIPPED, RECEIVED, CANCELLED
    delivery_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Inventory & Warehousing
CREATE TABLE warehouses (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    name VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    capacity_cubic_meters NUMERIC(10, 2) NOT NULL,
    used_capacity_cubic_meters NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_zones (
    id VARCHAR(50) PRIMARY KEY,
    warehouse_id VARCHAR(50) REFERENCES warehouses(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL, -- e.g., Ambient, Cold Storage, Hazardous
    capacity_limit NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_racks (
    id VARCHAR(50) PRIMARY KEY,
    zone_id VARCHAR(50) REFERENCES warehouse_zones(id) ON DELETE CASCADE,
    rack_number VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_shelves (
    id VARCHAR(50) PRIMARY KEY,
    rack_id VARCHAR(50) REFERENCES warehouse_racks(id) ON DELETE CASCADE,
    shelf_number VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_bins (
    id VARCHAR(50) PRIMARY KEY,
    shelf_id VARCHAR(50) REFERENCES warehouse_shelves(id) ON DELETE CASCADE,
    bin_number VARCHAR(10) NOT NULL,
    capacity_volume NUMERIC(5, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'EMPTY', -- EMPTY, PARTIAL, FULL
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_items (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    bin_id VARCHAR(50) REFERENCES warehouse_bins(id),
    sku VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    quantity INT DEFAULT 0,
    unit_price NUMERIC(12, 2) NOT NULL,
    reorder_level INT NOT NULL,
    reorder_quantity INT NOT NULL,
    batch_number VARCHAR(50),
    serial_number VARCHAR(100),
    expiry_date TIMESTAMP,
    status VARCHAR(20) DEFAULT 'IN_STOCK', -- IN_STOCK, LOW_STOCK, OUT_OF_STOCK
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id VARCHAR(50) REFERENCES inventory_items(id) ON DELETE CASCADE,
    transaction_type VARCHAR(20) NOT NULL, -- STOCK_IN, STOCK_OUT, TRANSFER
    quantity INT NOT NULL,
    source_bin_id VARCHAR(50) REFERENCES warehouse_bins(id),
    destination_bin_id VARCHAR(50) REFERENCES warehouse_bins(id),
    reference_id VARCHAR(50), -- e.g., Purchase Order ID or Customer Order ID
    performed_by VARCHAR(50) REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Customer Order Management
CREATE TABLE customer_orders (
    id VARCHAR(50) PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    customer_name VARCHAR(100) NOT NULL,
    customer_email VARCHAR(100) NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING', -- DRAFT, PENDING, APPROVED, PROCESSING, PACKED, SHIPPED, DELIVERED, CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(50) REFERENCES customer_orders(id) ON DELETE CASCADE,
    inventory_item_id VARCHAR(50) REFERENCES inventory_items(id),
    quantity INT NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL
);

-- 7. Logistics Management
CREATE TABLE shipments (
    id VARCHAR(50) PRIMARY KEY,
    order_id VARCHAR(50) REFERENCES customer_orders(id) ON DELETE CASCADE,
    carrier VARCHAR(100) NOT NULL,
    vehicle_number VARCHAR(50),
    driver_name VARCHAR(100),
    driver_phone VARCHAR(20),
    route_path TEXT, -- Coordinates path representation
    estimated_arrival TIMESTAMP,
    actual_arrival TIMESTAMP,
    status VARCHAR(20) DEFAULT 'CREATED', -- CREATED, PACKED, DISPATCHED, IN_TRANSIT, OUT_FOR_DELIVERY, DELIVERED
    proof_of_delivery_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shipment_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id VARCHAR(50) REFERENCES shipments(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    location VARCHAR(100) NOT NULL,
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10, 6),
    description TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Approval Workflow Configuration
CREATE TABLE approval_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(50) REFERENCES organizations(id),
    module VARCHAR(30) NOT NULL, -- PROCUREMENT, ORDER, INVENTORY_TRANSFER
    min_amount NUMERIC(15, 2) DEFAULT 0.00,
    max_amount NUMERIC(15, 2),
    required_role VARCHAR(30) NOT NULL,
    sequence_order INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_id VARCHAR(50) NOT NULL, -- PR ID, Order ID, etc.
    approver_id VARCHAR(50) REFERENCES users(id),
    action VARCHAR(20) NOT NULL, -- APPROVED, REJECTED
    remarks TEXT,
    sequence_order INT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Notification Center Logs
CREATE TABLE notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(30) DEFAULT 'INFO', -- INFO, ALERT, APPROVAL_REQUEST, STOCK_ALERT
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Indexes for performance optimization
CREATE INDEX idx_users_org ON users(organization_id);
CREATE INDEX idx_items_org ON inventory_items(organization_id);
CREATE INDEX idx_items_sku ON inventory_items(sku);
CREATE INDEX idx_orders_org ON customer_orders(organization_id);
CREATE INDEX idx_shipments_order ON shipments(order_id);
CREATE INDEX idx_audit_org ON audit_logs(organization_id);
CREATE INDEX idx_notifications_user ON notification_logs(user_id, is_read);
